name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install prerequisites
      run: sudo apt-get update && sudo apt-get install -y build-essential unzip cmake pkg-config libfontconfig1-dev clang libasound2-dev ninja-build libxcb-xfixes0-dev mesa-vulkan-drivers
    - name: Install ambient
      run: wget https://github.com/AmbientRun/Ambient/releases/download/v0.1.1/ambient-x86_64-unknown-linux-gnu.zip && unzip ambient-x86_64-unknown-linux-gnu.zip && echo "$pwd" && echo "$pwd" >> $GITHUB_PATH
    - name: Build
      run: ambient build
      
